<a href="https://colab.research.google.com/github/allatop/project/blob/main/DZnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Диагностическая работа по библиотеке NumPy**

#### **Задание 1: Векторизация в NumPy**


Напишите функцию, которая принимает два массива: одномерный массив `x` длины `n` и двумерный массив `A` размера `m×n`. Функция должна вычислить выражение `A @ x - 1` (матричное произведение A на x, затем вычитание 1 из каждого элемента результата и применение экспоненты) без использования циклов Python. Продемонстрируйте, насколько этот подход быстрее, чем решение с использованием циклов.

In [ ]:
import numpy as np
import time

def vectorized_operation(A, x):
    return np.exp(A @ x - 1)

def test_performance(n, m):

    x = np.random.rand(n)
    A = np.random.rand(m, n)

    start_time = time.time()
    result_vectorized = vectorized_operation(A, x)
    vectorized_time = time.time() - start_time

    start_time = time.time()
    result_loop = np.zeros(m)
    for i in range(m):
        result_loop[i] = np.exp(np.dot(A[i], x) - 1)
    loop_time = time.time() - start_time

    print(f"Векторизированный подход: {vectorized_time:.6f} секунд")
    print(f"Подход с циклами: {loop_time:.6f} секунд")

n = 1000
m = 10000
test_performance(n, m)

Векторизированный подход: 0.006758 секунд
Подход с циклами: 0.050885 секунд


#### **Задание 2: Индексация и маски**


Дан двумерный массив `data` с числовыми данными. Выполните следующие операции:
1. Создайте маску для всех элементов массива, которые больше среднего значения массива.
2. Замените все элементы, соответствующие этой маске, на их квадратные корни.
3. Остальные элементы замените на их квадраты.
4. Подсчитайте количество элементов, которые были заменены на квадратные корни.

In [ ]:
import numpy as np

def process_array(data):
    mean_value = np.mean(data)
    mask = data > mean_value
    result = np.copy(data)
    result[mask] = np.sqrt(result[mask])
    result[~mask] = result[~mask] ** 2
    count_sqrt_replaced = np.sum(mask)
    return result, count_sqrt_replaced

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_array, count = process_array(data)

print("Исходный массив:")
print(data)
print("\nОбработанный массив:")
print(result_array)
print("\nКоличество элементов, замененных на квадратные корни:", count)

Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Обработанный массив:
[[ 1  4  9]
 [16 25  2]
 [ 2  2  3]]

Количество элементов, замененных на квадратные корни: 4


#### **Задание 3. Структурированные массивы и группировка**


Создайте структурированный массив, представляющий информацию о студентах с полями: 'имя' (строка), 'возраст' (целое число) и 'оценки' (массив из 3 чисел с плавающей точкой). Выполните следующие операции:
1. Добавьте 10 студентов с разными данными.
2. Вычислите средний балл для каждого студента и добавьте это значение в новое поле 'средний_балл'.
3. Сгруппируйте студентов по возрасту и для каждой возрастной группы вычислите средний балл по всем предметам.
4. Отсортируйте студентов по убыванию среднего балла.

#### **Задание 4. Преобразование и изменение формы массивов**

Дан одномерный массив `data` длины `n*m`, где `n` и `m` - целые числа. Выполните следующие операции:
1. Преобразуйте его в двумерный массив размера `n×m`.
2. Транспонируйте полученный массив.
3. Примените функцию `np.where` для замены всех отрицательных значений на их абсолютные значения, а положительных значений на их квадратные корни.
4. Вычислите сумму элементов по каждой строке и столбцу. Определите строку с максимальной суммой и столбец с минимальной суммой.

In [ ]:
# Ваш код

#### **Задание 5. Оптимизация памяти и продвинутые операции**










Напишите функцию, которая генерирует матрицу размера `10000×10000`, заполненную случайными числами от 0 до 1, но использует минимально возможное количество памяти. Затем выполните следующие операции:
1. Не создавая копии матрицы, вычислите её определитель (если возможно) или оценку определителя.
2. Используя технику "memory views" или "strided arrays", извлеките каждый 10-й элемент по диагонали матрицы.
3. Создайте представление матрицы как трёхмерного массива размера `100×100×100` без копирования данных.
4. Продемонстрируйте, как можно применить batch-операцию (например, нормализацию) к каждому "срезу" этого трёхмерного представления.

Эти задания проверяют понимание ключевых возможностей NumPy, таких как векторизация вычислений, продвинутая индексация, работа с многомерными массивами, и оптимизация памяти

In [ ]:
# Ваш код